[[main]]
none = "none"

[[main]]
name = "posts"
pageRef = "posts"
identifier = "ypjBtk6mAq"
weight = 1

[[main]]
name = "about"
pageRef = "about"
identifier = "gQBfFwVnde"
weight = 2

[[main]]
name = "resume"
pageRef = "resume"
identifier = "0OsVjnhjKJ"
weight = 9999

[[footer]]
none = "none"
